### ISSUE TITLE
Rendering option in constructor

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_planar#3]
In the current implementation, rendering is invoked by the running in every time step (for example: https://github.com/maxspahn/gym_envs_planar/blob/4cb59ee52c96b07f3db584046875b1560ab2e3e4/examples/mobile_robot.py#L20).

It would be better and more compliant to other environments to have an option in the constructor [gym_envs_urdf](https://github.com/maxspahn/gym_envs_urdf/blob/cf7ad1318b3e596578b9b1accf40a758f4f14cda/examples/panda_reacher.py#L10).

I have already changed that for two environments, [/pointRobot/envs/acc.py](https://github.com/maxspahn/gym_envs_planar/blob/master/pointRobot/envs/acc.py) and [/nLinkReacher/envs/acc.py](https://github.com/maxspahn/gym_envs_planar/blob/master/nLinkReacher/envs/acc.py) in the commit 4cb59ee52c96b07f3db584046875b1560ab2e3e4.

That change should be applied for all environments to maintain easy switching between environment control types.

**Comment by alxschwrz** [comment]
I'll work on it.
