### ISSUE TITLE
Ground_robot_arm not running due to error in reset() function

### ISSUE THREAD

**Issue by alxschwrz** [maxspahn/gym_envs_planar#6]
When executing `examples/ground_robot_arm.py`, an error is thrown, due to wrong amount of arguments passed to the function `reset()`

**Error message**: 
ob = env.reset(np.array([0.0, 0.0, 0.0, 0.0]), np.array([1.0, 0.0]), np.array([0.0]))
TypeError: reset() takes 1 positional argument but 4 were given

similar issue as in #5

**Comment by maxspahn** [comment]
Similar error as #5

**Comment by maxspahn** [comment]
Related error in [groundRobot:continuous_dynamics](https://github.com/maxspahn/gym_envs_planar/blob/b06d8df42452e66cd391f0f566cc1c9dd02cd7ae/groundRobots/envs/acc_dd_arm.py#L96).

The continuous dynamics do not reflect the implementation of differential drive in the other examples. 
This needs major revision.

**Comment by alxschwrz** [comment]
similar problem occurs when trying to run the `ground_robot.py` in the acceleration environments
`groundRobots/env/acc.py` and
`groundRobots/env/acc_dd.py`

**To reproduce:** 
I changed line 7 in the `ground_robot.py` example to either
`env = gym.make('ground-robot-acc-v0', render=True, dt=0.01)` or
`env = gym.make('ground-robot-acc-v0', render=True, dt=0.01)` 

**Error message for both environments:**
return self.env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'pos'

The arguments, which are passed to the reset function differ between acceleration and velocity environments.
